#############################################
###                                       ###
###  NeuralEmbeddings Pretraining Config  ###
###                                       ###
#############################################

seed: null

### Weights & Biases Integration ###

wandb_mode: "online" # ["online", "offline", "disabled"]

### Training ###

train_epochs: 1
learning_rate: 0.001

train_method: "CPC"

cpc_params:
  embedding_dim: 256
  n_pred_steps: 12
  scheduler_enabled: True

### Model ###

model:
  save_path: "../models/cpc_model.pt"