#############################################
###                                       ###
###  NeuralEmbeddings Pretraining Config  ###
###                                       ###
#############################################

seed: null

### Weights & Biases Integration ###

wandb_mode: "online" # ["online", "offline", "disabled"]

### Training ###

train_epochs: 10
learning_rate: 0.001

train_method: "MSM"

# The method params only need to be defined
# for the method being used
msm_params:
  mask_prob: 0.15
  min_mask_len: 1
  max_mask_len: 1

  # These learning rates are overwriten by the global
  # lr if not defined or null
  sc_lr: 0.001
  mc_lr: 0.001
  calib_lr: 0.001
  scheduler_enabled: True
  phase_decay: 0.1
  
batch_size: 8

# Number of samples = unit size * batch size
# The number of sequential points that are sampled for a single example
primary_unit_size: 5000
calibration_unit_size: 20000

# Number of samples used to fit preprocessors
preprocess_fit_samples: 5
# Save path for preprocessed models
preprocessed_model_path: "../models/msm_sweep_preprocessors_long.pkl"

# TODO: Change to full data
# Save paths for preprocessed data
train_val_preprocessed: "data/sweep_train_preprocessed_long"
test_preprocessed: "data/sweep_test_preprocessed_long"

model:
  max_primary_input_len: 5000 # Needs to be changes to primary unit size
  max_calibration_input_len: 20000 # Needs to be changed to calibration unit size
  embedding_dim: 64
  # Single channel module params
  single_channel_module:
    enabled: True # [True, False]

    # Conv
    filter_size: 200
    stride: 150

  mixed_channel_module:
    enabled: True # [True, False]

    # Conv
    filter_size: 200
    stride: 150

  ### Calibration Model ###
  
  # Calibration module params
  calibration_module:
    enabled: True # [True, False]

    filter_size: 1000
    stride: 900
    feedforward_dim: 256