#############################################
###                                       ###
###  NeuralEmbeddings Pretraining Config  ###
###                                       ###
#############################################


seed: 8


### Training ###


train_epochs: 10
learning_rate: 0.0001
log_interval: 16
device: "cpu"

train_method: "MSM"

# The method params only need to be defined
# for the method being used
msm_params:
  mask_prob: 0.1
  min_mask_len: 2
  max_mask_len: 4
  
cpc_params:
  wip: True

swav_params:
  wip: True


### Data ###

data_type: "MEG" # Valid values: [MEG, EEG]

# Number of samples = unit size * batch size
# seq_unit_size: 2048
# The number of sequential points that are sampled for a single example
primary_unit_size: 512
calibration_unit_size: 1024

# Total sequential points per batch =
# batch_size * primary_unit_size + calibration_unit_size
batch_size: 2


val_split: 0.05 # Percentage of data used for validation
test_split: 0.15 # Percentage of data used for testing


### Model ###


model:
  save_path: "../models/test_model.pt"

  max_primary_input_len: 512
  max_calibration_input_len: 1024
  embedding_dim: 16
  channel_combine_func: "mean" # Valid values: [mean, logsumexp]

  ### Primary Model ###

  # Single channel module params
  single_channel_module:
    enabled: True

    # Conv
    filter_size: 32
    stride: 16

    # Transformer
    n_layers: 2
    dropout: 0.4
    n_head: 2 # N heads for the attention
    feedforward_dim: 256

  # Mixed channel module parameters
  mixed_channel_module:
    enabled: True

    # Conv (NOT USED unless the single channel module is disabled)
    filter_size: 32
    stride: 16

    # Transformer
    n_layers: 2
    dropout: 0.4
    n_head: 2 # N heads for the attention
    feedforward_dim: 256

  ### Calibration Model ###
  
  # Calibration module params
  calibration_module:
    enabled: True

    # Conv
    filter_size: 64
    stride: 32

    # Transformer
    n_layers: 2
    dropout: 0.4
    n_head: 2 # N heads for the attention
    feedforward_dim: 256


# PREPROCESSING STUFF

data_file_type: ".fif"
data_type: "MEG" # Valid values: [MEG, EEG]

train_dir: "./train_datasets"
test_dir: "./test_datasets"

common_sfreq: 1000.0
high_pass_cut_off: 0.1


use_standardization: False
use_normalization: True
use_high_pass_filter: False

use_ica: False

ica:
  n_components: 0.95
  random_state: 0
  max_iter: 500


train_val_preprocessed: "train_preprocessed_runs"
test_preprocessed: "test_preprocessed_runs"

train_val_info: 'dataset_information_train.data'
test_info: 'dataset_information_test.data'