#############################################
###                                       ###
###  NeuralEmbeddings Pretraining Config  ###
###                                       ###
#############################################

### TODO ###

seed: null

### Weights & Biases Integration ###

wandb_mode: "offline" # ["online", "offline", "disabled"]

### Training ###

device: "cpu"

train_epochs: 4
epoch_early_cutoff: 0.1
learning_rate: 0.001
log_interval: 4
val_interval: 16

train_method: "CPC"

# The method params only need to be defined
# for the method being used
msm_params:
  mask_prob: 0.1
  min_mask_len: 2
  max_mask_len: 4

  # These learning rates are overwriten by the global
  # lr if not defined or null
  sc_lr: 0.001
  mc_lr: 0.001
  calib_lr: 0.001
  scheduler_enabled: True
  phase_decay: 0.1
  
cpc_params:
  embedding_dim: 64
  n_pred_steps: 2
  mi_seq_radius: null
  scheduler_enabled: True

# Number of samples = unit size * batch size
# The number of sequential points that are sampled for a single example
primary_unit_size: 1000
calibration_unit_size: 2000

### Data ###

batch_size: 4

### Preprocessing ###

train_dir: "data/small_train_datasets"
test_dir: "data/small_test_datasets"

use_standardization: True
use_normalization: False
use_high_pass_filter: True
use_ica: False

# Save path for preprocessed models
preprocessed_model_path: "../models/test_preprocessors.pkl"

# Save paths for preprocessed data
train_val_preprocessed: "data/small_train_preprocessed"
test_preprocessed: "data/small_test_preprocessed"

### Model ###

model:
  save_path: "../models/test_model.pt"

  max_primary_input_len: 1000
  max_calibration_input_len: 2000