#############################################
###                                       ###
###  NeuralEmbeddings Pretraining Config  ###
###                                       ###
#############################################


seed: 8


### Training ###


train_epochs: 10
learning_rate: 0.0001
log_interval: 16
val_interval: 1024
device: "cuda"

train_method: "MSM"

# The method params only need to be defined
# for the method being used
msm_params:
  mask_prob: 0.1
  min_mask_len: 2
  max_mask_len: 4
  
cpc_params:
  wip: True

swav_params:
  wip: True


### Data ###


data_type: "MEG" # Valid values: [MEG, EEG]

# Number of samples = unit size * batch size
# seq_unit_size: 2048
# The number of sequential points that are sampled for a single example
primary_unit_size: 512
calibration_unit_size: 1024

# Total sequential points per batch =
# batch_size * primary_unit_size + calibration_unit_size
batch_size: 2


val_split: 0.05 # Percentage of data used for validation
test_split: 0.15 # Percentage of data used for testing


### Preprocessing ###


data_file_type: ".fif"

train_dir: "data/train_datasets"
test_dir: "data/test_datasets"

common_sfreq: 1000.0
high_pass_cut_off: 0.1

# Only one of standardization and normalization can be used
use_standardization: False
use_normalization: True
use_high_pass_filter: False

# ICA
use_ica: False
ica:
  n_components: 0.95
  max_iter: 500

# Save paths for preprocessed data
train_val_preprocessed: "data/train_preprocessed"
test_preprocessed: "data/test_preprocessed"

# Save filename for metadata (wihout filetype)
train_val_info: "dataset_info"
test_info: "dataset_info"


### Model ###


model:
  save_path: "../models/test_model.pt"

  max_primary_input_len: 512
  max_calibration_input_len: 1024
  embedding_dim: 16
  channel_combine_func: "mean" # Valid values: [mean, logsumexp]

  ### Primary Model ###

  # Single channel module params
  single_channel_module:
    enabled: True

    # Conv
    filter_size: 32
    stride: 16

    # Transformer
    n_layers: 2
    dropout: 0.4
    n_head: 2 # N heads for the attention
    feedforward_dim: 256

  # Mixed channel module parameters
  mixed_channel_module:
    enabled: True

    # Conv (NOT USED unless the single channel module is disabled)
    filter_size: 32
    stride: 16

    # Transformer
    n_layers: 2
    dropout: 0.4
    n_head: 2 # N heads for the attention
    feedforward_dim: 256

  ### Calibration Model ###
  
  # Calibration module params
  calibration_module:
    enabled: True

    # Conv
    filter_size: 64
    stride: 32

    # Transformer
    n_layers: 2
    dropout: 0.4
    n_head: 2 # N heads for the attention
    feedforward_dim: 256