model:
  max_input_seq_len: 1024
  input_channels: 1
  embedding_dim: 16

  # Convolution layer parameters
  conv:
    enabled: True

    filter_size: 32
    stride: 16

  # Single channel encoder parameters
  single_channel_encoder:
    enabled: True

    n_layers: 2
    dropout: 0.5
    n_head: 2 # N heads for the attention

  # Mixed channel encoder parameters
  mixed_channel_encoder:
    enabled: True

training:
  # Number of samples = unit size * batch size
  train_batch_size: 1
  val_batch_size: 1
  test_batch_size: 1

  val_split: 0.05 # Percentage of data used for validation
  test_split: 0.15 # Percentage of data used for testing

data:
  unit_size: 1024 # How many sequential points are counted as
               # a single unit for indexing
  data_type: "MEG" # Valid values: [MEG, EEG]
